### PR TITLE
Valid date refactor

### LINKED ISSUE #22: Refactor the utils.validDate function
While linting the utils.py module I came across this function and i wanted to work on it, but didn't want to mix simple code linting with actually changing the logic of the function.
# Plan of attack:
-  Write up a set of tests to clearly define the function's behavior
-  Refactor the internal code to make it more readable.  I think python's datetime module will prove useful helper methods.
-  I would like to have the function return a boolean instead of a status code of 0 or 1 in the future.  To support this all other callers will need to check for a boolean instead of an int as the return value.

### PR DESCRIPTION
**Pull request by cgoodale**
@kwhitehall I think this version is a little more concise and we get to lean on the python core datetime library for valid datetime formatting.

Resolves #22 

Tag me with any comments or questions about what I did.

### CODE REVIEW

**Comment by kwhitehall** [comment]
Nice one @cgoodale! Do you think we can extend the functionality to include YYYYMMDDHHmm quickly before merging? The reason I ask is because the kind of analysis the GTG does should incorporate using sub-hourly data.

**Comment by cgoodale** [comment]
It's a simple fix to do.  Does that mean we will always expect minutes, or if they are not given we merely assume they mean 00 minutes?

**Comment by kwhitehall** [comment]
Yip (repeating what you said) we should always expect YYYYMMDDHH, but if someone decides they are using hourly data and enter YYYYMMDDHH, we should force it to be YYYYMMDDHH00

**Comment by cgoodale** [comment]
@kwhitehall I changed it up a bit.  Now we only support datestrings with length 10 (YYYYMMDDhh) or 12 (YYYYMMDDhhmm).  I think it reads fairly well now, and I included a test for the minutes version.

**Comment by kwhitehall** [comment]
Thanks @cgoodale! Let's get it in there!

**Comment by kwhitehall** [comment]
Merged PR 31. Close issue #31

**Pull request merged**
