### PR TITLE
GTG-37 create a number of timing tests between the main components of GTG

### PR DESCRIPTION
**Pull request by kwhitehall**
- prints out the timing in seconds between the major components of the GTG to both the standard output and a file in the folder with the results

### CODE REVIEW

**Comment by kwhitehall** [comment]
@cgoodale Is this what you were thinking?

**Comment by kwhitehall** [comment]
Merged. Closes issue #37.

**Comment by cgoodale** [comment]
@kwhitehall this is exactly what i had in mind, and i like that you also output the timing results to a file.

**Comment by kwhitehall** [comment]
@cgoodale SWEET!

**Pull request merged**
